#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

PS1="\[\033[1;92m\]\w\[\033[0m\]> "

bind "set completion-ignore-case on"
bind "set show-all-if-ambiguous on"

alias ls='eza --icons --group-directories-first'
alias ll='eza -lbF --git --icons --total-size --group-directories-first'
alias lt='eza --tree --level=2 --icons'

alias z2j='trans -4 -s zh -t ja'
alias z2e='trans -4 -s zh -t en'
alias e2z='trans -4 -s en -t zh'
alias e2j='trans -4 -s en -t ja'
alias j2z='trans -4 -s ja -t zh'
alias j2e='trans -4 -s ja -t en'
alias bash-fork='alacritty msg create-window --working-directory $(pwd) -e bash'
alias d='jj diff'
alias docker='sudo nerdctl --address /run/k3s/containerd/containerd.sock --namespace k8s.io'

function y() {
    local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
    yazi "$@" --cwd-file="$tmp"
    IFS= read -r -d '' cwd < "$tmp"
    [ -n "$cwd" ] && [ "$cwd" != "$PWD" ] && builtin cd -- "$cwd"
    rm -f -- "$tmp"
}

function br {
    local cmd cmd_file code
    cmd_file=$(mktemp)
    if broot --outcmd "$cmd_file" "$@"; then
        cmd=$(<"$cmd_file")
        command rm -f "$cmd_file"
        eval "$cmd"
    else
        code=$?
        command rm -f "$cmd_file"
        return "$code"
    fi
}

[[ $- == *i* ]] && source -- "$(blesh-share)"/ble.sh --attach=none

eval "$(zoxide init bash)"
alias za='zoxide add .'

eval "$(atuin init bash)"

[[ ! ''${BLE_VERSION-} ]] || ble-attach

export PATH="$HOME/.local/bin:$PATH"

[ -f "$HOME/.local/share/venv/bin/activate" ] && source "$HOME/.local/share/venv/bin/activate"
