#!/usr/bin/env bash
set -euo pipefail

target_dir="${1:-.}"

for dir in "$target_dir"/*; do
    if [ -d "$dir" ] && [ -d "$dir/.jj" ]; then
        if [[ -n $(cd "$dir" && jj log -r '(@ ~ empty()) | (@- ~ remote_bookmarks())' --no-graph 2>/dev/null) ]]; then
            clean_name=$(basename "$dir")
            echo -e "\n\033[1;33m=== $clean_name ===\033[0m"
            (cd "$dir" && jj st)
        fi
    fi
done
echo ""
