#!/usr/bin/env bash

set -e

if [[ $# -eq 0 ]]; then
  read -e -p 'Search (pkg|opt|hm|sty|mn): ' input
  [[ -z "$input" ]] && exit 0

  set -- $input
fi

cmd="${1:-pkg}"
shift || true
query="$*"

case "$cmd" in
  pkg) url="https://search.nixos.org/packages?query=" ;;
  opt) url="https://search.nixos.org/options?query=" ;;
  hm)  url="https://home-manager-options.extranix.com/?release=release-25.11&query=" ;;
  sty) url="https://nix-community.github.io/stylix/configuration.html?search=" ;;
  mn)  url="https://mynixos.com/search?q=" ;;
  *)
    query="$cmd $query"
    url="https://search.nixos.org/packages?query="
    ;;
esac

[[ -z "$query" ]] && exit 0

xdg-open "${url}$(jq -sRr @uri <<<"$query")" &
