#!/usr/bin/env bash

set -e

if [[ $# -eq 0 ]]; then
  echo 'Search (pkg|opt|hm|sty|mn)'
  exit 0
fi

cmd="${1:-pkg}"
shift || true
query="$*"

case "$cmd" in
  pkg) url="https://search.nixos.org/packages?channel=unstable&query=" ;;
  opt) url="https://search.nixos.org/options?channel=unstable&query=" ;;
  hm)  url="https://home-manager-options.extranix.com/?release=master&query=" ;;
  sty) url="https://nix-community.github.io/stylix/configuration.html?search=" ;;
  mn)  url="https://mynixos.com/search?q=" ;;
  *)
    query="$cmd $query"
    url="https://search.nixos.org/packages?channel=unstable&query="
    ;;
esac

[[ -z "$query" ]] && exit 0

xdg-open "${url}$(jq -sRr @uri <<<"$query")" &
