mode: rule
mixed-port: 7897
allow-lan: false
log-level: info
ipv6: false
external-controller: 127.0.0.1:9090
secret: ""
unified-delay: true
external-controller-unix: /run/user/1000/clash-verge-rev/verge-mihomo.sock
geox-url:
  geoip: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geoip.dat"
  geosite: "https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/geosite.dat"
  mmdb: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-Country.mmdb"
  asn: "https://cdn.jsdelivr.net/gh/Loyalsoldier/geoip@release/GeoLite2-ASN.mmdb"
profile:
  tracing: true
  store-selected: true
experimental:
  sniff-tls-sni: true
tun:
  auto-detect-interface: true
  auto-route: true
  device: Mihomo
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 1500
  stack: gvisor
  strict-route: false
  enable: true
dns:
  use-hosts: true
  use-system-hosts: true
  default-nameserver:
  - tls://223.5.5.5
  - tls://8.8.8.8
  - tls://1.1.1.1
  nameserver-policy:
    "geosite:cn,private":
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  nameserver:
  - https://dns.google/dns-query
  - https://cloudflare-dns.com/dns-query
  direct-nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  direct-nameserver-follow-policy: false
  proxy-server-nameserver:
  - https://doh.pub/dns-query
  - https://dns.alidns.com/dns-query
  enable: true
  enhanced-mode: fake-ip
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.arpa'
  - time.*.com
  - ntp.*.com
  - time.*.com
  - +.market.xiaomi.com
  - localhost.ptlogin2.qq.com
  - '*.msftncsi.com'
  - www.msftconnecttest.com
  fake-ip-filter-mode: blacklist
  fake-ip-range: 198.18.0.1/16
  ipv6: false
  listen: 127.0.0.1:53
  prefer-h3: false
  respect-rules: false
external-controller-cors:
  allow-private-network: true
  allow-origins:
  - '*'
clash-for-android:
  append-system-dns: false
proxy-providers:
  sub2:
    type: file
    path: /var/lib/private/mihomo/providers/sub2.yaml
    health-check:
      enable: false
      interval: 1200
      url: https://www.apple.com/library/test/success.html
  sub3:
    type: file
    path: /var/lib/private/mihomo/providers/sub3.yaml
    health-check:
      enable: false
      interval: 1200
      url: https://www.apple.com/library/test/success.html
proxy-groups:
  - name: SELECT
    type: select
    use:
      - sub2
      - sub3
    proxies:
      - ANYTLS
      - VLESS
      - DIRECT
  - name: ANYTLS
    type: url-test
    url: https://www.apple.com/library/test/success.html
    interval: 1200
    lazy: true
    use:
      - sub2
    filter: "AnyTLS"
    exclude-filter: "香港|HongKong"
  - name: VLESS
    type: url-test
    url: https://www.apple.com/library/test/success.html
    interval: 1200
    lazy: true
    use:
      - sub3
    exclude-filter: "香港|HongKong"
rules:
  - GEOSITE,category-ads-all,REJECT

  - DOMAIN,www.apple.com,SELECT
  - DOMAIN,browserleaks.com,SELECT
  - IP-CIDR,47.110.248.69/32,DIRECT,no-resolve
  - IP-CIDR,101.37.64.91/32,DIRECT,no-resolve
  - IP-CIDR,101.37.156.175/32,DIRECT,no-resolve
  - IP-CIDR,45.137.181.152/32,DIRECT,no-resolve

  - GEOSITE,cn,DIRECT
  - GEOSITE,private,DIRECT
  - GEOSITE,steam@cn,DIRECT
  - GEOSITE,category-games@cn,DIRECT

  - DOMAIN-SUFFIX,mianshiya.com,DIRECT
  - DOMAIN,copypaste.me,DIRECT
  - DOMAIN,mirrors.tuna.tsinghua.edu.cn,DIRECT
  - DOMAIN-SUFFIX,feishu.cn,DIRECT
  - DOMAIN-SUFFIX,feishucdn.com,DIRECT
  - DOMAIN,dns.alidns.com,DIRECT
  - DOMAIN,doh.pub,DIRECT

  - GEOSITE,geolocation-!cn,SELECT
  - GEOSITE,google,SELECT
  - GEOSITE,youtube,SELECT
  - GEOSITE,telegram,SELECT
  - GEOSITE,netflix,SELECT
  - GEOSITE,github,SELECT

  - GEOIP,private,DIRECT,no-resolve
  - GEOIP,telegram,SELECT
  - GEOIP,cn,DIRECT

  - MATCH,SELECT
